// Code generated by capnpc-go. DO NOT EDIT.

package main

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type Way capnp.Struct

// Way_TypeID is the unique identifier for the type Way.
const Way_TypeID = 0xa4b9c59286b69600

func NewWay(s *capnp.Segment) (Way, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 4})
	return Way(st), err
}

func NewRootWay(s *capnp.Segment) (Way, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 4})
	return Way(st), err
}

func ReadRootWay(msg *capnp.Message) (Way, error) {
	root, err := msg.Root()
	return Way(root.Struct()), err
}

func (s Way) String() string {
	str, _ := text.Marshal(0xa4b9c59286b69600, capnp.Struct(s))
	return str
}

func (s Way) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Way) DecodeFromPtr(p capnp.Ptr) Way {
	return Way(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Way) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Way) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Way) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Way) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Way) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Way) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Way) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Way) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Way) Ref() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Way) HasRef() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Way) RefBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Way) SetRef(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Way) MaxSpeed() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Way) SetMaxSpeed(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Way) MinLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Way) SetMinLat(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Way) MinLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s Way) SetMinLon(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s Way) MaxLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s Way) SetMaxLat(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

func (s Way) MaxLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(32))
}

func (s Way) SetMaxLon(v float64) {
	capnp.Struct(s).SetUint64(32, math.Float64bits(v))
}

func (s Way) Nodes() (Coordinates_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return Coordinates_List(p.List()), err
}

func (s Way) HasNodes() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Way) SetNodes(v Coordinates_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewNodes sets the nodes field to a newly
// allocated Coordinates_List, preferring placement in s's segment.
func (s Way) NewNodes(n int32) (Coordinates_List, error) {
	l, err := NewCoordinates_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Coordinates_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s Way) Lanes() uint8 {
	return capnp.Struct(s).Uint8(40)
}

func (s Way) SetLanes(v uint8) {
	capnp.Struct(s).SetUint8(40, v)
}

func (s Way) AdvisorySpeed() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(48))
}

func (s Way) SetAdvisorySpeed(v float64) {
	capnp.Struct(s).SetUint64(48, math.Float64bits(v))
}

func (s Way) Hazard() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Way) HasHazard() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Way) HazardBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Way) SetHazard(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Way) OneWay() bool {
	return capnp.Struct(s).Bit(328)
}

func (s Way) SetOneWay(v bool) {
	capnp.Struct(s).SetBit(328, v)
}

// Way_List is a list of Way.
type Way_List = capnp.StructList[Way]

// NewWay creates a new list of Way.
func NewWay_List(s *capnp.Segment, sz int32) (Way_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 56, PointerCount: 4}, sz)
	return capnp.StructList[Way](l), err
}

// Way_Future is a wrapper for a Way promised by a client call.
type Way_Future struct{ *capnp.Future }

func (f Way_Future) Struct() (Way, error) {
	p, err := f.Future.Ptr()
	return Way(p.Struct()), err
}

type Coordinates capnp.Struct

// Coordinates_TypeID is the unique identifier for the type Coordinates.
const Coordinates_TypeID = 0x922b57c60c6a46d1

func NewCoordinates(s *capnp.Segment) (Coordinates, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Coordinates(st), err
}

func NewRootCoordinates(s *capnp.Segment) (Coordinates, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Coordinates(st), err
}

func ReadRootCoordinates(msg *capnp.Message) (Coordinates, error) {
	root, err := msg.Root()
	return Coordinates(root.Struct()), err
}

func (s Coordinates) String() string {
	str, _ := text.Marshal(0x922b57c60c6a46d1, capnp.Struct(s))
	return str
}

func (s Coordinates) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Coordinates) DecodeFromPtr(p capnp.Ptr) Coordinates {
	return Coordinates(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Coordinates) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Coordinates) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Coordinates) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Coordinates) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Coordinates) Latitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Coordinates) SetLatitude(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Coordinates) Longitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Coordinates) SetLongitude(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

// Coordinates_List is a list of Coordinates.
type Coordinates_List = capnp.StructList[Coordinates]

// NewCoordinates creates a new list of Coordinates.
func NewCoordinates_List(s *capnp.Segment, sz int32) (Coordinates_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[Coordinates](l), err
}

// Coordinates_Future is a wrapper for a Coordinates promised by a client call.
type Coordinates_Future struct{ *capnp.Future }

func (f Coordinates_Future) Struct() (Coordinates, error) {
	p, err := f.Future.Ptr()
	return Coordinates(p.Struct()), err
}

type Offline capnp.Struct

// Offline_TypeID is the unique identifier for the type Offline.
const Offline_TypeID = 0xcb5ff253617678e0

func NewOffline(s *capnp.Segment) (Offline, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 2})
	return Offline(st), err
}

func NewRootOffline(s *capnp.Segment) (Offline, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 2})
	return Offline(st), err
}

func ReadRootOffline(msg *capnp.Message) (Offline, error) {
	root, err := msg.Root()
	return Offline(root.Struct()), err
}

func (s Offline) String() string {
	str, _ := text.Marshal(0xcb5ff253617678e0, capnp.Struct(s))
	return str
}

func (s Offline) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Offline) DecodeFromPtr(p capnp.Ptr) Offline {
	return Offline(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Offline) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Offline) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Offline) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Offline) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Offline) MinLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Offline) SetMinLat(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Offline) MinLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Offline) SetMinLon(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Offline) MaxLat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s Offline) SetMaxLat(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s Offline) MaxLon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s Offline) SetMaxLon(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

func (s Offline) Ways() (Way_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Way_List(p.List()), err
}

func (s Offline) HasWays() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Offline) SetWays(v Way_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewWays sets the ways field to a newly
// allocated Way_List, preferring placement in s's segment.
func (s Offline) NewWays(n int32) (Way_List, error) {
	l, err := NewWay_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Way_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Offline) Overlap() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(32))
}

func (s Offline) SetOverlap(v float64) {
	capnp.Struct(s).SetUint64(32, math.Float64bits(v))
}

func (s Offline) StopSigns() (StopSign_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return StopSign_List(p.List()), err
}

func (s Offline) HasStopSigns() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Offline) SetStopSigns(v StopSign_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewStopSigns sets the stopSigns field to a newly
// allocated StopSign_List, preferring placement in s's segment.
func (s Offline) NewStopSigns(n int32) (StopSign_List, error) {
	l, err := NewStopSign_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return StopSign_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// Offline_List is a list of Offline.
type Offline_List = capnp.StructList[Offline]

// NewOffline creates a new list of Offline.
func NewOffline_List(s *capnp.Segment, sz int32) (Offline_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 40, PointerCount: 2}, sz)
	return capnp.StructList[Offline](l), err
}

// Offline_Future is a wrapper for a Offline promised by a client call.
type Offline_Future struct{ *capnp.Future }

func (f Offline_Future) Struct() (Offline, error) {
	p, err := f.Future.Ptr()
	return Offline(p.Struct()), err
}

type StopSign capnp.Struct

// StopSign_TypeID is the unique identifier for the type StopSign.
const StopSign_TypeID = 0xc68ea0083bc4f222

func NewStopSign(s *capnp.Segment) (StopSign, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StopSign(st), err
}

func NewRootStopSign(s *capnp.Segment) (StopSign, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StopSign(st), err
}

func ReadRootStopSign(msg *capnp.Message) (StopSign, error) {
	root, err := msg.Root()
	return StopSign(root.Struct()), err
}

func (s StopSign) String() string {
	str, _ := text.Marshal(0xc68ea0083bc4f222, capnp.Struct(s))
	return str
}

func (s StopSign) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StopSign) DecodeFromPtr(p capnp.Ptr) StopSign {
	return StopSign(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StopSign) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StopSign) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StopSign) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StopSign) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StopSign) Location() (Coordinates, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Coordinates(p.Struct()), err
}

func (s StopSign) HasLocation() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StopSign) SetLocation(v Coordinates) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewLocation sets the location field to a newly
// allocated Coordinates struct, preferring placement in s's segment.
func (s StopSign) NewLocation() (Coordinates, error) {
	ss, err := NewCoordinates(capnp.Struct(s).Segment())
	if err != nil {
		return Coordinates{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// StopSign_List is a list of StopSign.
type StopSign_List = capnp.StructList[StopSign]

// NewStopSign creates a new list of StopSign.
func NewStopSign_List(s *capnp.Segment, sz int32) (StopSign_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StopSign](l), err
}

// StopSign_Future is a wrapper for a StopSign promised by a client call.
type StopSign_Future struct{ *capnp.Future }

func (f StopSign_Future) Struct() (StopSign, error) {
	p, err := f.Future.Ptr()
	return StopSign(p.Struct()), err
}
func (p StopSign_Future) Location() Coordinates_Future {
	return Coordinates_Future{Future: p.Future.Field(0, nil)}
}

const schema_da3a0d9284ca402f = "x\xda\xa4\x94\xcbk$U\x14\xc6\xcfwo\xf5#\xe9" +
	"N'E\xd5\xc2\x85\xd0\x92U\x8c\xa8\x89q\xd5\x06:" +
	"*J\x0c\x01s\xad\x84D\x88\xe8%]\x1d[:U" +
	"Mw'\xe9\x96\x80\x0aQ\x14|@/\\\xbb\x10\\" +
	"\x09*f\x98\x0c\x09d \xc9\x0c3\x8ba\x86\xd9\xcc" +
	"\x90\x81\xfc\x0dY\xcdjj8\xb7\xe9G\xc8rvu" +
	"\x7f\xe7\xabsN\x9d\xf3\xd5\x9d\xb8\x87\x19kr\xe8\x96" +
	" \xa1^\x89\xc5\xa3\xfb\x1f~\x95>]~\xadE*" +
	"\x03\x11\xbd9sg\xb75\x94{LV\x82\xc8\xf9\x08" +
	"\x0f\x9c%\xf0\x93\xc26\xe1\xd9\xef\xd7~h\x9d\xec\xff" +
	"\xa92H\xf4\x941#\xddC\xcb9d\xe9\xd4>\xfe" +
	"\x12\x84h\xf4\xe2\xf8\x9d\xe4\x1f\xbf\x9e\x92\x9dA\x9f\xd8" +
	"d\xfb\xde\xba\xe1\xfcb^\xfb\xc9\xca\x13\xa2\xf3\xc6\x96" +
	"\xf6.>\xbf\xcb=\xc4\xfa\xc4\x82%\x7f[\xff9{" +
	",\x9e\xfa\xd7\xfa\x0d\xf4z\x14\x16\x8b\xe5R\xe0\xbf!" +
	"\xd6t%\xa8\xe4\xde\x0f\xc3j\xa1\x14\xe8\xba\x8f\xda\x02" +
	"\xa0\x92\xd2\"\xb2@d\xbf:G\xa4\xc6$\xd4\xdb\x02" +
	"6\xe0\x82\xe1\xe4'DjBBM\x0bDe]/" +
	"\xd57\x0b>\x11!E\x02)BT\x0e\x83u\x86\x04" +
	"\xbf\xcb:%\xd1.\xb9\xac\xd1\xe4R\x13\x9dR\xce\xbb" +
	"\x18'\xf2\xa6!\xe1\xcd\xa2W\xcd\xf9\x00\xa3D\xde\x0c" +
	"\xf3y\x08@\xb8\x10f\xb0sD\xde,\xe3E\x96K" +
	"\xb8\x90f\xcc9\"o\x9e\xf9\x0asK\xb8\xb0\x88\x9c" +
	"%\xc3\x17\x98\xaf2\x8fI\x171\"\xe7S\xc3\x17\x99" +
	"\x7f\xc1<n\xb9\x88\x139\x9f\x19\xbe\xc2\xbc\xc0<!" +
	"\\3x\x8d\xb7\x88\xbcU\xe6\x0d\xe6\xc91\x17I\"" +
	"g\xd3\xf0\x0a\xf3\x1d\xe6\x03q\x17\x03DN\x13U\"" +
	"\xaf\xc1|\x97\xf9\xa0t1H\xe4|g\xf2\xef0\xff" +
	"\x11\x02\x93\xa9Y\xb8H\xf1fM\xe0[\x0e\xfc\x0c\x81" +
	"\xe1@o\xf8H\x93@\x9a\x90\xa8\xfa\xc5\xces\xb4\xa1" +
	"\x1b^\xc5\xf7\x0b}\x93\xcfo\x94\x82y]\xbft\x0c" +
	"\x83\xdeQ7.Eu\xa3/\x9a\x0d\xc2\x82_C\x86" +
	"\xb0 \x81\x91\x9e\xab\x09\x0c\xb3e\x1d\xf85\xc4I " +
	"N\x88ta\xabT\x0b\xabM\xca\x9a\x1e\xba9\xbf\xd4" +
	"_\xebj\xa1\xd3c>\x0c\xfce\xdd\x04H\x00WM" +
	"\xe0\xd5\xf3a\xc5+\xad\x07\xec\x04\xabk\xba!6]" +
	"ZB\xbd\xc4\xfe\x0a\xd7t\xbd\x14\x06\xfc\x95\x97\x9b\x1a" +
	"\xb9\x9a\xf0\xe3b\xd6\x9c9\xdf\xcb\xdd|{9\"\xf5" +
	"\x8f\x84:\xe83\xf1>\xc3\xff%\xd4\x91\x80-\xda\xa6" +
	"\xb2\x0f\x19^\x97P\xc7\xec(i\x1ce\xdfdx " +
	"\xa1n\x0b\xc02n\xb2O\xc6\x89\xd4\x91\x84:c+" +
	"Y\xc6J\xf6\xa3\xf7\x88\xd4C\x09u\xce>\x82\xf1\x91" +
	"\xfd\x84\x7f\x963\x09\xf5T\xbc\xd0z\x86\xb7u\xb3\xb7" +
	"\x9d\xce=\xd2\xde\xcd7\xe1\x96_-\xebJ\xf7g\xab" +
	"\xd5\xdbs%\xf4-\xb4{\x9d\xb4_z\x1e\x00\x00\xff" +
	"\xff\\~\xf4\xa0"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_da3a0d9284ca402f,
		Nodes: []uint64{
			0x922b57c60c6a46d1,
			0xa4b9c59286b69600,
			0xc68ea0083bc4f222,
			0xcb5ff253617678e0,
		},
		Compressed: true,
	})
}
