// Code generated by capnpc-go. DO NOT EDIT.

package custom

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type CustomReserved0 capnp.Struct

// CustomReserved0_TypeID is the unique identifier for the type CustomReserved0.
const CustomReserved0_TypeID = 0x81c2f05a394cf4af

func NewCustomReserved0(s *capnp.Segment) (CustomReserved0, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved0(st), err
}

func NewRootCustomReserved0(s *capnp.Segment) (CustomReserved0, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved0(st), err
}

func ReadRootCustomReserved0(msg *capnp.Message) (CustomReserved0, error) {
	root, err := msg.Root()
	return CustomReserved0(root.Struct()), err
}

func (s CustomReserved0) String() string {
	str, _ := text.Marshal(0x81c2f05a394cf4af, capnp.Struct(s))
	return str
}

func (s CustomReserved0) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved0) DecodeFromPtr(p capnp.Ptr) CustomReserved0 {
	return CustomReserved0(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved0) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved0) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved0) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved0) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved0_List is a list of CustomReserved0.
type CustomReserved0_List = capnp.StructList[CustomReserved0]

// NewCustomReserved0 creates a new list of CustomReserved0.
func NewCustomReserved0_List(s *capnp.Segment, sz int32) (CustomReserved0_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved0](l), err
}

// CustomReserved0_Future is a wrapper for a CustomReserved0 promised by a client call.
type CustomReserved0_Future struct{ *capnp.Future }

func (f CustomReserved0_Future) Struct() (CustomReserved0, error) {
	p, err := f.Future.Ptr()
	return CustomReserved0(p.Struct()), err
}

type CustomReserved1 capnp.Struct

// CustomReserved1_TypeID is the unique identifier for the type CustomReserved1.
const CustomReserved1_TypeID = 0xaedffd8f31e7b55d

func NewCustomReserved1(s *capnp.Segment) (CustomReserved1, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved1(st), err
}

func NewRootCustomReserved1(s *capnp.Segment) (CustomReserved1, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved1(st), err
}

func ReadRootCustomReserved1(msg *capnp.Message) (CustomReserved1, error) {
	root, err := msg.Root()
	return CustomReserved1(root.Struct()), err
}

func (s CustomReserved1) String() string {
	str, _ := text.Marshal(0xaedffd8f31e7b55d, capnp.Struct(s))
	return str
}

func (s CustomReserved1) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved1) DecodeFromPtr(p capnp.Ptr) CustomReserved1 {
	return CustomReserved1(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved1) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved1) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved1) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved1) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved1_List is a list of CustomReserved1.
type CustomReserved1_List = capnp.StructList[CustomReserved1]

// NewCustomReserved1 creates a new list of CustomReserved1.
func NewCustomReserved1_List(s *capnp.Segment, sz int32) (CustomReserved1_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved1](l), err
}

// CustomReserved1_Future is a wrapper for a CustomReserved1 promised by a client call.
type CustomReserved1_Future struct{ *capnp.Future }

func (f CustomReserved1_Future) Struct() (CustomReserved1, error) {
	p, err := f.Future.Ptr()
	return CustomReserved1(p.Struct()), err
}

type CustomReserved2 capnp.Struct

// CustomReserved2_TypeID is the unique identifier for the type CustomReserved2.
const CustomReserved2_TypeID = 0xf35cc4560bbf6ec2

func NewCustomReserved2(s *capnp.Segment) (CustomReserved2, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved2(st), err
}

func NewRootCustomReserved2(s *capnp.Segment) (CustomReserved2, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved2(st), err
}

func ReadRootCustomReserved2(msg *capnp.Message) (CustomReserved2, error) {
	root, err := msg.Root()
	return CustomReserved2(root.Struct()), err
}

func (s CustomReserved2) String() string {
	str, _ := text.Marshal(0xf35cc4560bbf6ec2, capnp.Struct(s))
	return str
}

func (s CustomReserved2) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved2) DecodeFromPtr(p capnp.Ptr) CustomReserved2 {
	return CustomReserved2(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved2) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved2) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved2) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved2) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved2_List is a list of CustomReserved2.
type CustomReserved2_List = capnp.StructList[CustomReserved2]

// NewCustomReserved2 creates a new list of CustomReserved2.
func NewCustomReserved2_List(s *capnp.Segment, sz int32) (CustomReserved2_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved2](l), err
}

// CustomReserved2_Future is a wrapper for a CustomReserved2 promised by a client call.
type CustomReserved2_Future struct{ *capnp.Future }

func (f CustomReserved2_Future) Struct() (CustomReserved2, error) {
	p, err := f.Future.Ptr()
	return CustomReserved2(p.Struct()), err
}

type CustomReserved3 capnp.Struct

// CustomReserved3_TypeID is the unique identifier for the type CustomReserved3.
const CustomReserved3_TypeID = 0xda96579883444c35

func NewCustomReserved3(s *capnp.Segment) (CustomReserved3, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved3(st), err
}

func NewRootCustomReserved3(s *capnp.Segment) (CustomReserved3, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved3(st), err
}

func ReadRootCustomReserved3(msg *capnp.Message) (CustomReserved3, error) {
	root, err := msg.Root()
	return CustomReserved3(root.Struct()), err
}

func (s CustomReserved3) String() string {
	str, _ := text.Marshal(0xda96579883444c35, capnp.Struct(s))
	return str
}

func (s CustomReserved3) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved3) DecodeFromPtr(p capnp.Ptr) CustomReserved3 {
	return CustomReserved3(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved3) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved3) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved3) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved3) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved3_List is a list of CustomReserved3.
type CustomReserved3_List = capnp.StructList[CustomReserved3]

// NewCustomReserved3 creates a new list of CustomReserved3.
func NewCustomReserved3_List(s *capnp.Segment, sz int32) (CustomReserved3_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved3](l), err
}

// CustomReserved3_Future is a wrapper for a CustomReserved3 promised by a client call.
type CustomReserved3_Future struct{ *capnp.Future }

func (f CustomReserved3_Future) Struct() (CustomReserved3, error) {
	p, err := f.Future.Ptr()
	return CustomReserved3(p.Struct()), err
}

type CustomReserved4 capnp.Struct

// CustomReserved4_TypeID is the unique identifier for the type CustomReserved4.
const CustomReserved4_TypeID = 0x80ae746ee2596b11

func NewCustomReserved4(s *capnp.Segment) (CustomReserved4, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved4(st), err
}

func NewRootCustomReserved4(s *capnp.Segment) (CustomReserved4, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved4(st), err
}

func ReadRootCustomReserved4(msg *capnp.Message) (CustomReserved4, error) {
	root, err := msg.Root()
	return CustomReserved4(root.Struct()), err
}

func (s CustomReserved4) String() string {
	str, _ := text.Marshal(0x80ae746ee2596b11, capnp.Struct(s))
	return str
}

func (s CustomReserved4) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved4) DecodeFromPtr(p capnp.Ptr) CustomReserved4 {
	return CustomReserved4(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved4) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved4) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved4) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved4) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved4_List is a list of CustomReserved4.
type CustomReserved4_List = capnp.StructList[CustomReserved4]

// NewCustomReserved4 creates a new list of CustomReserved4.
func NewCustomReserved4_List(s *capnp.Segment, sz int32) (CustomReserved4_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved4](l), err
}

// CustomReserved4_Future is a wrapper for a CustomReserved4 promised by a client call.
type CustomReserved4_Future struct{ *capnp.Future }

func (f CustomReserved4_Future) Struct() (CustomReserved4, error) {
	p, err := f.Future.Ptr()
	return CustomReserved4(p.Struct()), err
}

type CustomReserved5 capnp.Struct

// CustomReserved5_TypeID is the unique identifier for the type CustomReserved5.
const CustomReserved5_TypeID = 0xa5cd762cd951a455

func NewCustomReserved5(s *capnp.Segment) (CustomReserved5, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved5(st), err
}

func NewRootCustomReserved5(s *capnp.Segment) (CustomReserved5, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved5(st), err
}

func ReadRootCustomReserved5(msg *capnp.Message) (CustomReserved5, error) {
	root, err := msg.Root()
	return CustomReserved5(root.Struct()), err
}

func (s CustomReserved5) String() string {
	str, _ := text.Marshal(0xa5cd762cd951a455, capnp.Struct(s))
	return str
}

func (s CustomReserved5) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved5) DecodeFromPtr(p capnp.Ptr) CustomReserved5 {
	return CustomReserved5(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved5) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved5) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved5) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved5) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved5_List is a list of CustomReserved5.
type CustomReserved5_List = capnp.StructList[CustomReserved5]

// NewCustomReserved5 creates a new list of CustomReserved5.
func NewCustomReserved5_List(s *capnp.Segment, sz int32) (CustomReserved5_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved5](l), err
}

// CustomReserved5_Future is a wrapper for a CustomReserved5 promised by a client call.
type CustomReserved5_Future struct{ *capnp.Future }

func (f CustomReserved5_Future) Struct() (CustomReserved5, error) {
	p, err := f.Future.Ptr()
	return CustomReserved5(p.Struct()), err
}

type CustomReserved6 capnp.Struct

// CustomReserved6_TypeID is the unique identifier for the type CustomReserved6.
const CustomReserved6_TypeID = 0xf98d843bfd7004a3

func NewCustomReserved6(s *capnp.Segment) (CustomReserved6, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved6(st), err
}

func NewRootCustomReserved6(s *capnp.Segment) (CustomReserved6, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved6(st), err
}

func ReadRootCustomReserved6(msg *capnp.Message) (CustomReserved6, error) {
	root, err := msg.Root()
	return CustomReserved6(root.Struct()), err
}

func (s CustomReserved6) String() string {
	str, _ := text.Marshal(0xf98d843bfd7004a3, capnp.Struct(s))
	return str
}

func (s CustomReserved6) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved6) DecodeFromPtr(p capnp.Ptr) CustomReserved6 {
	return CustomReserved6(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved6) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved6) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved6) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved6) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved6_List is a list of CustomReserved6.
type CustomReserved6_List = capnp.StructList[CustomReserved6]

// NewCustomReserved6 creates a new list of CustomReserved6.
func NewCustomReserved6_List(s *capnp.Segment, sz int32) (CustomReserved6_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved6](l), err
}

// CustomReserved6_Future is a wrapper for a CustomReserved6 promised by a client call.
type CustomReserved6_Future struct{ *capnp.Future }

func (f CustomReserved6_Future) Struct() (CustomReserved6, error) {
	p, err := f.Future.Ptr()
	return CustomReserved6(p.Struct()), err
}

type CustomReserved7 capnp.Struct

// CustomReserved7_TypeID is the unique identifier for the type CustomReserved7.
const CustomReserved7_TypeID = 0xb86e6369214c01c8

func NewCustomReserved7(s *capnp.Segment) (CustomReserved7, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved7(st), err
}

func NewRootCustomReserved7(s *capnp.Segment) (CustomReserved7, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved7(st), err
}

func ReadRootCustomReserved7(msg *capnp.Message) (CustomReserved7, error) {
	root, err := msg.Root()
	return CustomReserved7(root.Struct()), err
}

func (s CustomReserved7) String() string {
	str, _ := text.Marshal(0xb86e6369214c01c8, capnp.Struct(s))
	return str
}

func (s CustomReserved7) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved7) DecodeFromPtr(p capnp.Ptr) CustomReserved7 {
	return CustomReserved7(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved7) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved7) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved7) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved7) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved7_List is a list of CustomReserved7.
type CustomReserved7_List = capnp.StructList[CustomReserved7]

// NewCustomReserved7 creates a new list of CustomReserved7.
func NewCustomReserved7_List(s *capnp.Segment, sz int32) (CustomReserved7_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved7](l), err
}

// CustomReserved7_Future is a wrapper for a CustomReserved7 promised by a client call.
type CustomReserved7_Future struct{ *capnp.Future }

func (f CustomReserved7_Future) Struct() (CustomReserved7, error) {
	p, err := f.Future.Ptr()
	return CustomReserved7(p.Struct()), err
}

type CustomReserved8 capnp.Struct

// CustomReserved8_TypeID is the unique identifier for the type CustomReserved8.
const CustomReserved8_TypeID = 0xf416ec09499d9d19

func NewCustomReserved8(s *capnp.Segment) (CustomReserved8, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved8(st), err
}

func NewRootCustomReserved8(s *capnp.Segment) (CustomReserved8, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved8(st), err
}

func ReadRootCustomReserved8(msg *capnp.Message) (CustomReserved8, error) {
	root, err := msg.Root()
	return CustomReserved8(root.Struct()), err
}

func (s CustomReserved8) String() string {
	str, _ := text.Marshal(0xf416ec09499d9d19, capnp.Struct(s))
	return str
}

func (s CustomReserved8) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved8) DecodeFromPtr(p capnp.Ptr) CustomReserved8 {
	return CustomReserved8(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved8) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved8) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved8) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved8) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved8_List is a list of CustomReserved8.
type CustomReserved8_List = capnp.StructList[CustomReserved8]

// NewCustomReserved8 creates a new list of CustomReserved8.
func NewCustomReserved8_List(s *capnp.Segment, sz int32) (CustomReserved8_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved8](l), err
}

// CustomReserved8_Future is a wrapper for a CustomReserved8 promised by a client call.
type CustomReserved8_Future struct{ *capnp.Future }

func (f CustomReserved8_Future) Struct() (CustomReserved8, error) {
	p, err := f.Future.Ptr()
	return CustomReserved8(p.Struct()), err
}

type CustomReserved9 capnp.Struct

// CustomReserved9_TypeID is the unique identifier for the type CustomReserved9.
const CustomReserved9_TypeID = 0xa1680744031fdb2d

func NewCustomReserved9(s *capnp.Segment) (CustomReserved9, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved9(st), err
}

func NewRootCustomReserved9(s *capnp.Segment) (CustomReserved9, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved9(st), err
}

func ReadRootCustomReserved9(msg *capnp.Message) (CustomReserved9, error) {
	root, err := msg.Root()
	return CustomReserved9(root.Struct()), err
}

func (s CustomReserved9) String() string {
	str, _ := text.Marshal(0xa1680744031fdb2d, capnp.Struct(s))
	return str
}

func (s CustomReserved9) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved9) DecodeFromPtr(p capnp.Ptr) CustomReserved9 {
	return CustomReserved9(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved9) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved9) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved9) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved9) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved9_List is a list of CustomReserved9.
type CustomReserved9_List = capnp.StructList[CustomReserved9]

// NewCustomReserved9 creates a new list of CustomReserved9.
func NewCustomReserved9_List(s *capnp.Segment, sz int32) (CustomReserved9_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved9](l), err
}

// CustomReserved9_Future is a wrapper for a CustomReserved9 promised by a client call.
type CustomReserved9_Future struct{ *capnp.Future }

func (f CustomReserved9_Future) Struct() (CustomReserved9, error) {
	p, err := f.Future.Ptr()
	return CustomReserved9(p.Struct()), err
}

type CustomReserved10 capnp.Struct

// CustomReserved10_TypeID is the unique identifier for the type CustomReserved10.
const CustomReserved10_TypeID = 0xcb9fd56c7057593a

func NewCustomReserved10(s *capnp.Segment) (CustomReserved10, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved10(st), err
}

func NewRootCustomReserved10(s *capnp.Segment) (CustomReserved10, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved10(st), err
}

func ReadRootCustomReserved10(msg *capnp.Message) (CustomReserved10, error) {
	root, err := msg.Root()
	return CustomReserved10(root.Struct()), err
}

func (s CustomReserved10) String() string {
	str, _ := text.Marshal(0xcb9fd56c7057593a, capnp.Struct(s))
	return str
}

func (s CustomReserved10) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved10) DecodeFromPtr(p capnp.Ptr) CustomReserved10 {
	return CustomReserved10(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved10) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved10) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved10) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved10) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved10_List is a list of CustomReserved10.
type CustomReserved10_List = capnp.StructList[CustomReserved10]

// NewCustomReserved10 creates a new list of CustomReserved10.
func NewCustomReserved10_List(s *capnp.Segment, sz int32) (CustomReserved10_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved10](l), err
}

// CustomReserved10_Future is a wrapper for a CustomReserved10 promised by a client call.
type CustomReserved10_Future struct{ *capnp.Future }

func (f CustomReserved10_Future) Struct() (CustomReserved10, error) {
	p, err := f.Future.Ptr()
	return CustomReserved10(p.Struct()), err
}

type CustomReserved11 capnp.Struct

// CustomReserved11_TypeID is the unique identifier for the type CustomReserved11.
const CustomReserved11_TypeID = 0xc2243c65e0340384

func NewCustomReserved11(s *capnp.Segment) (CustomReserved11, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved11(st), err
}

func NewRootCustomReserved11(s *capnp.Segment) (CustomReserved11, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved11(st), err
}

func ReadRootCustomReserved11(msg *capnp.Message) (CustomReserved11, error) {
	root, err := msg.Root()
	return CustomReserved11(root.Struct()), err
}

func (s CustomReserved11) String() string {
	str, _ := text.Marshal(0xc2243c65e0340384, capnp.Struct(s))
	return str
}

func (s CustomReserved11) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved11) DecodeFromPtr(p capnp.Ptr) CustomReserved11 {
	return CustomReserved11(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved11) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved11) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved11) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved11) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved11_List is a list of CustomReserved11.
type CustomReserved11_List = capnp.StructList[CustomReserved11]

// NewCustomReserved11 creates a new list of CustomReserved11.
func NewCustomReserved11_List(s *capnp.Segment, sz int32) (CustomReserved11_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved11](l), err
}

// CustomReserved11_Future is a wrapper for a CustomReserved11 promised by a client call.
type CustomReserved11_Future struct{ *capnp.Future }

func (f CustomReserved11_Future) Struct() (CustomReserved11, error) {
	p, err := f.Future.Ptr()
	return CustomReserved11(p.Struct()), err
}

type CustomReserved12 capnp.Struct

// CustomReserved12_TypeID is the unique identifier for the type CustomReserved12.
const CustomReserved12_TypeID = 0x9ccdc8676701b412

func NewCustomReserved12(s *capnp.Segment) (CustomReserved12, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved12(st), err
}

func NewRootCustomReserved12(s *capnp.Segment) (CustomReserved12, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved12(st), err
}

func ReadRootCustomReserved12(msg *capnp.Message) (CustomReserved12, error) {
	root, err := msg.Root()
	return CustomReserved12(root.Struct()), err
}

func (s CustomReserved12) String() string {
	str, _ := text.Marshal(0x9ccdc8676701b412, capnp.Struct(s))
	return str
}

func (s CustomReserved12) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved12) DecodeFromPtr(p capnp.Ptr) CustomReserved12 {
	return CustomReserved12(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved12) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved12) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved12) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved12) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved12_List is a list of CustomReserved12.
type CustomReserved12_List = capnp.StructList[CustomReserved12]

// NewCustomReserved12 creates a new list of CustomReserved12.
func NewCustomReserved12_List(s *capnp.Segment, sz int32) (CustomReserved12_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved12](l), err
}

// CustomReserved12_Future is a wrapper for a CustomReserved12 promised by a client call.
type CustomReserved12_Future struct{ *capnp.Future }

func (f CustomReserved12_Future) Struct() (CustomReserved12, error) {
	p, err := f.Future.Ptr()
	return CustomReserved12(p.Struct()), err
}

type CustomReserved13 capnp.Struct

// CustomReserved13_TypeID is the unique identifier for the type CustomReserved13.
const CustomReserved13_TypeID = 0xcd96dafb67a082d0

func NewCustomReserved13(s *capnp.Segment) (CustomReserved13, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved13(st), err
}

func NewRootCustomReserved13(s *capnp.Segment) (CustomReserved13, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved13(st), err
}

func ReadRootCustomReserved13(msg *capnp.Message) (CustomReserved13, error) {
	root, err := msg.Root()
	return CustomReserved13(root.Struct()), err
}

func (s CustomReserved13) String() string {
	str, _ := text.Marshal(0xcd96dafb67a082d0, capnp.Struct(s))
	return str
}

func (s CustomReserved13) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved13) DecodeFromPtr(p capnp.Ptr) CustomReserved13 {
	return CustomReserved13(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved13) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved13) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved13) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved13) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved13_List is a list of CustomReserved13.
type CustomReserved13_List = capnp.StructList[CustomReserved13]

// NewCustomReserved13 creates a new list of CustomReserved13.
func NewCustomReserved13_List(s *capnp.Segment, sz int32) (CustomReserved13_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved13](l), err
}

// CustomReserved13_Future is a wrapper for a CustomReserved13 promised by a client call.
type CustomReserved13_Future struct{ *capnp.Future }

func (f CustomReserved13_Future) Struct() (CustomReserved13, error) {
	p, err := f.Future.Ptr()
	return CustomReserved13(p.Struct()), err
}

type CustomReserved14 capnp.Struct

// CustomReserved14_TypeID is the unique identifier for the type CustomReserved14.
const CustomReserved14_TypeID = 0xb057204d7deadf3f

func NewCustomReserved14(s *capnp.Segment) (CustomReserved14, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved14(st), err
}

func NewRootCustomReserved14(s *capnp.Segment) (CustomReserved14, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved14(st), err
}

func ReadRootCustomReserved14(msg *capnp.Message) (CustomReserved14, error) {
	root, err := msg.Root()
	return CustomReserved14(root.Struct()), err
}

func (s CustomReserved14) String() string {
	str, _ := text.Marshal(0xb057204d7deadf3f, capnp.Struct(s))
	return str
}

func (s CustomReserved14) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved14) DecodeFromPtr(p capnp.Ptr) CustomReserved14 {
	return CustomReserved14(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved14) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved14) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved14) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved14) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved14_List is a list of CustomReserved14.
type CustomReserved14_List = capnp.StructList[CustomReserved14]

// NewCustomReserved14 creates a new list of CustomReserved14.
func NewCustomReserved14_List(s *capnp.Segment, sz int32) (CustomReserved14_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved14](l), err
}

// CustomReserved14_Future is a wrapper for a CustomReserved14 promised by a client call.
type CustomReserved14_Future struct{ *capnp.Future }

func (f CustomReserved14_Future) Struct() (CustomReserved14, error) {
	p, err := f.Future.Ptr()
	return CustomReserved14(p.Struct()), err
}

type CustomReserved15 capnp.Struct

// CustomReserved15_TypeID is the unique identifier for the type CustomReserved15.
const CustomReserved15_TypeID = 0xbd443b539493bc68

func NewCustomReserved15(s *capnp.Segment) (CustomReserved15, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved15(st), err
}

func NewRootCustomReserved15(s *capnp.Segment) (CustomReserved15, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved15(st), err
}

func ReadRootCustomReserved15(msg *capnp.Message) (CustomReserved15, error) {
	root, err := msg.Root()
	return CustomReserved15(root.Struct()), err
}

func (s CustomReserved15) String() string {
	str, _ := text.Marshal(0xbd443b539493bc68, capnp.Struct(s))
	return str
}

func (s CustomReserved15) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved15) DecodeFromPtr(p capnp.Ptr) CustomReserved15 {
	return CustomReserved15(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved15) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved15) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved15) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved15) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved15_List is a list of CustomReserved15.
type CustomReserved15_List = capnp.StructList[CustomReserved15]

// NewCustomReserved15 creates a new list of CustomReserved15.
func NewCustomReserved15_List(s *capnp.Segment, sz int32) (CustomReserved15_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved15](l), err
}

// CustomReserved15_Future is a wrapper for a CustomReserved15 promised by a client call.
type CustomReserved15_Future struct{ *capnp.Future }

func (f CustomReserved15_Future) Struct() (CustomReserved15, error) {
	p, err := f.Future.Ptr()
	return CustomReserved15(p.Struct()), err
}

type CustomReserved16 capnp.Struct

// CustomReserved16_TypeID is the unique identifier for the type CustomReserved16.
const CustomReserved16_TypeID = 0xfc6241ed8877b611

func NewCustomReserved16(s *capnp.Segment) (CustomReserved16, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved16(st), err
}

func NewRootCustomReserved16(s *capnp.Segment) (CustomReserved16, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved16(st), err
}

func ReadRootCustomReserved16(msg *capnp.Message) (CustomReserved16, error) {
	root, err := msg.Root()
	return CustomReserved16(root.Struct()), err
}

func (s CustomReserved16) String() string {
	str, _ := text.Marshal(0xfc6241ed8877b611, capnp.Struct(s))
	return str
}

func (s CustomReserved16) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved16) DecodeFromPtr(p capnp.Ptr) CustomReserved16 {
	return CustomReserved16(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved16) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved16) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved16) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved16) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved16_List is a list of CustomReserved16.
type CustomReserved16_List = capnp.StructList[CustomReserved16]

// NewCustomReserved16 creates a new list of CustomReserved16.
func NewCustomReserved16_List(s *capnp.Segment, sz int32) (CustomReserved16_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved16](l), err
}

// CustomReserved16_Future is a wrapper for a CustomReserved16 promised by a client call.
type CustomReserved16_Future struct{ *capnp.Future }

func (f CustomReserved16_Future) Struct() (CustomReserved16, error) {
	p, err := f.Future.Ptr()
	return CustomReserved16(p.Struct()), err
}

type MapdDownloadLocationDetails capnp.Struct

// MapdDownloadLocationDetails_TypeID is the unique identifier for the type MapdDownloadLocationDetails.
const MapdDownloadLocationDetails_TypeID = 0xff889853e7b0987f

func NewMapdDownloadLocationDetails(s *capnp.Segment) (MapdDownloadLocationDetails, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdDownloadLocationDetails(st), err
}

func NewRootMapdDownloadLocationDetails(s *capnp.Segment) (MapdDownloadLocationDetails, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdDownloadLocationDetails(st), err
}

func ReadRootMapdDownloadLocationDetails(msg *capnp.Message) (MapdDownloadLocationDetails, error) {
	root, err := msg.Root()
	return MapdDownloadLocationDetails(root.Struct()), err
}

func (s MapdDownloadLocationDetails) String() string {
	str, _ := text.Marshal(0xff889853e7b0987f, capnp.Struct(s))
	return str
}

func (s MapdDownloadLocationDetails) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdDownloadLocationDetails) DecodeFromPtr(p capnp.Ptr) MapdDownloadLocationDetails {
	return MapdDownloadLocationDetails(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdDownloadLocationDetails) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdDownloadLocationDetails) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdDownloadLocationDetails) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdDownloadLocationDetails) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdDownloadLocationDetails) Location() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MapdDownloadLocationDetails) HasLocation() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdDownloadLocationDetails) LocationBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MapdDownloadLocationDetails) SetLocation(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s MapdDownloadLocationDetails) TotalFiles() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s MapdDownloadLocationDetails) SetTotalFiles(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s MapdDownloadLocationDetails) DownloadedFiles() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s MapdDownloadLocationDetails) SetDownloadedFiles(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

// MapdDownloadLocationDetails_List is a list of MapdDownloadLocationDetails.
type MapdDownloadLocationDetails_List = capnp.StructList[MapdDownloadLocationDetails]

// NewMapdDownloadLocationDetails creates a new list of MapdDownloadLocationDetails.
func NewMapdDownloadLocationDetails_List(s *capnp.Segment, sz int32) (MapdDownloadLocationDetails_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[MapdDownloadLocationDetails](l), err
}

// MapdDownloadLocationDetails_Future is a wrapper for a MapdDownloadLocationDetails promised by a client call.
type MapdDownloadLocationDetails_Future struct{ *capnp.Future }

func (f MapdDownloadLocationDetails_Future) Struct() (MapdDownloadLocationDetails, error) {
	p, err := f.Future.Ptr()
	return MapdDownloadLocationDetails(p.Struct()), err
}

type MapdDownloadProgress capnp.Struct

// MapdDownloadProgress_TypeID is the unique identifier for the type MapdDownloadProgress.
const MapdDownloadProgress_TypeID = 0xfaa35dcac85073a2

func NewMapdDownloadProgress(s *capnp.Segment) (MapdDownloadProgress, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return MapdDownloadProgress(st), err
}

func NewRootMapdDownloadProgress(s *capnp.Segment) (MapdDownloadProgress, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return MapdDownloadProgress(st), err
}

func ReadRootMapdDownloadProgress(msg *capnp.Message) (MapdDownloadProgress, error) {
	root, err := msg.Root()
	return MapdDownloadProgress(root.Struct()), err
}

func (s MapdDownloadProgress) String() string {
	str, _ := text.Marshal(0xfaa35dcac85073a2, capnp.Struct(s))
	return str
}

func (s MapdDownloadProgress) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdDownloadProgress) DecodeFromPtr(p capnp.Ptr) MapdDownloadProgress {
	return MapdDownloadProgress(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdDownloadProgress) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdDownloadProgress) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdDownloadProgress) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdDownloadProgress) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdDownloadProgress) Active() bool {
	return capnp.Struct(s).Bit(0)
}

func (s MapdDownloadProgress) SetActive(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s MapdDownloadProgress) Cancelled() bool {
	return capnp.Struct(s).Bit(1)
}

func (s MapdDownloadProgress) SetCancelled(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

func (s MapdDownloadProgress) TotalFiles() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s MapdDownloadProgress) SetTotalFiles(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s MapdDownloadProgress) DownloadedFiles() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s MapdDownloadProgress) SetDownloadedFiles(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s MapdDownloadProgress) Locations() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s MapdDownloadProgress) HasLocations() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdDownloadProgress) SetLocations(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewLocations sets the locations field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s MapdDownloadProgress) NewLocations(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s MapdDownloadProgress) LocationDetails() (MapdDownloadLocationDetails_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return MapdDownloadLocationDetails_List(p.List()), err
}

func (s MapdDownloadProgress) HasLocationDetails() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s MapdDownloadProgress) SetLocationDetails(v MapdDownloadLocationDetails_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewLocationDetails sets the locationDetails field to a newly
// allocated MapdDownloadLocationDetails_List, preferring placement in s's segment.
func (s MapdDownloadProgress) NewLocationDetails(n int32) (MapdDownloadLocationDetails_List, error) {
	l, err := NewMapdDownloadLocationDetails_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return MapdDownloadLocationDetails_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// MapdDownloadProgress_List is a list of MapdDownloadProgress.
type MapdDownloadProgress_List = capnp.StructList[MapdDownloadProgress]

// NewMapdDownloadProgress creates a new list of MapdDownloadProgress.
func NewMapdDownloadProgress_List(s *capnp.Segment, sz int32) (MapdDownloadProgress_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2}, sz)
	return capnp.StructList[MapdDownloadProgress](l), err
}

// MapdDownloadProgress_Future is a wrapper for a MapdDownloadProgress promised by a client call.
type MapdDownloadProgress_Future struct{ *capnp.Future }

func (f MapdDownloadProgress_Future) Struct() (MapdDownloadProgress, error) {
	p, err := f.Future.Ptr()
	return MapdDownloadProgress(p.Struct()), err
}

type MapdPathPoint capnp.Struct

// MapdPathPoint_TypeID is the unique identifier for the type MapdPathPoint.
const MapdPathPoint_TypeID = 0xd6f78acca1bc3939

func NewMapdPathPoint(s *capnp.Segment) (MapdPathPoint, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return MapdPathPoint(st), err
}

func NewRootMapdPathPoint(s *capnp.Segment) (MapdPathPoint, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return MapdPathPoint(st), err
}

func ReadRootMapdPathPoint(msg *capnp.Message) (MapdPathPoint, error) {
	root, err := msg.Root()
	return MapdPathPoint(root.Struct()), err
}

func (s MapdPathPoint) String() string {
	str, _ := text.Marshal(0xd6f78acca1bc3939, capnp.Struct(s))
	return str
}

func (s MapdPathPoint) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdPathPoint) DecodeFromPtr(p capnp.Ptr) MapdPathPoint {
	return MapdPathPoint(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdPathPoint) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdPathPoint) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdPathPoint) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdPathPoint) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdPathPoint) Latitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s MapdPathPoint) SetLatitude(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s MapdPathPoint) Longitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s MapdPathPoint) SetLongitude(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s MapdPathPoint) Curvature() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(16))
}

func (s MapdPathPoint) SetCurvature(v float32) {
	capnp.Struct(s).SetUint32(16, math.Float32bits(v))
}

func (s MapdPathPoint) TargetVelocity() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(20))
}

func (s MapdPathPoint) SetTargetVelocity(v float32) {
	capnp.Struct(s).SetUint32(20, math.Float32bits(v))
}

// MapdPathPoint_List is a list of MapdPathPoint.
type MapdPathPoint_List = capnp.StructList[MapdPathPoint]

// NewMapdPathPoint creates a new list of MapdPathPoint.
func NewMapdPathPoint_List(s *capnp.Segment, sz int32) (MapdPathPoint_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0}, sz)
	return capnp.StructList[MapdPathPoint](l), err
}

// MapdPathPoint_Future is a wrapper for a MapdPathPoint promised by a client call.
type MapdPathPoint_Future struct{ *capnp.Future }

func (f MapdPathPoint_Future) Struct() (MapdPathPoint, error) {
	p, err := f.Future.Ptr()
	return MapdPathPoint(p.Struct()), err
}

type MapdExtendedOut capnp.Struct

// MapdExtendedOut_TypeID is the unique identifier for the type MapdExtendedOut.
const MapdExtendedOut_TypeID = 0xa30662f84033036c

func NewMapdExtendedOut(s *capnp.Segment) (MapdExtendedOut, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return MapdExtendedOut(st), err
}

func NewRootMapdExtendedOut(s *capnp.Segment) (MapdExtendedOut, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return MapdExtendedOut(st), err
}

func ReadRootMapdExtendedOut(msg *capnp.Message) (MapdExtendedOut, error) {
	root, err := msg.Root()
	return MapdExtendedOut(root.Struct()), err
}

func (s MapdExtendedOut) String() string {
	str, _ := text.Marshal(0xa30662f84033036c, capnp.Struct(s))
	return str
}

func (s MapdExtendedOut) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdExtendedOut) DecodeFromPtr(p capnp.Ptr) MapdExtendedOut {
	return MapdExtendedOut(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdExtendedOut) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdExtendedOut) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdExtendedOut) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdExtendedOut) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdExtendedOut) DownloadProgress() (MapdDownloadProgress, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return MapdDownloadProgress(p.Struct()), err
}

func (s MapdExtendedOut) HasDownloadProgress() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdExtendedOut) SetDownloadProgress(v MapdDownloadProgress) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewDownloadProgress sets the downloadProgress field to a newly
// allocated MapdDownloadProgress struct, preferring placement in s's segment.
func (s MapdExtendedOut) NewDownloadProgress() (MapdDownloadProgress, error) {
	ss, err := NewMapdDownloadProgress(capnp.Struct(s).Segment())
	if err != nil {
		return MapdDownloadProgress{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s MapdExtendedOut) Settings() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s MapdExtendedOut) HasSettings() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s MapdExtendedOut) SettingsBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s MapdExtendedOut) SetSettings(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s MapdExtendedOut) Path() (MapdPathPoint_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return MapdPathPoint_List(p.List()), err
}

func (s MapdExtendedOut) HasPath() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s MapdExtendedOut) SetPath(v MapdPathPoint_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewPath sets the path field to a newly
// allocated MapdPathPoint_List, preferring placement in s's segment.
func (s MapdExtendedOut) NewPath(n int32) (MapdPathPoint_List, error) {
	l, err := NewMapdPathPoint_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return MapdPathPoint_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// MapdExtendedOut_List is a list of MapdExtendedOut.
type MapdExtendedOut_List = capnp.StructList[MapdExtendedOut]

// NewMapdExtendedOut creates a new list of MapdExtendedOut.
func NewMapdExtendedOut_List(s *capnp.Segment, sz int32) (MapdExtendedOut_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[MapdExtendedOut](l), err
}

// MapdExtendedOut_Future is a wrapper for a MapdExtendedOut promised by a client call.
type MapdExtendedOut_Future struct{ *capnp.Future }

func (f MapdExtendedOut_Future) Struct() (MapdExtendedOut, error) {
	p, err := f.Future.Ptr()
	return MapdExtendedOut(p.Struct()), err
}
func (p MapdExtendedOut_Future) DownloadProgress() MapdDownloadProgress_Future {
	return MapdDownloadProgress_Future{Future: p.Future.Field(0, nil)}
}

type MapdInputType uint16

// MapdInputType_TypeID is the unique identifier for the type MapdInputType.
const MapdInputType_TypeID = 0x859f26628fc24358

// Values of MapdInputType.
const (
	MapdInputType_download                               MapdInputType = 0
	MapdInputType_setTargetLateralAccel                  MapdInputType = 1
	MapdInputType_setSpeedLimitOffset                    MapdInputType = 2
	MapdInputType_setSpeedLimitControl                   MapdInputType = 3
	MapdInputType_setMapCurveSpeedControl                MapdInputType = 4
	MapdInputType_setVisionCurveSpeedControl             MapdInputType = 5
	MapdInputType_setLogLevel                            MapdInputType = 6
	MapdInputType_setVisionCurveTargetLatA               MapdInputType = 7
	MapdInputType_setVisionCurveMinTargetV               MapdInputType = 8
	MapdInputType_reloadSettings                         MapdInputType = 9
	MapdInputType_saveSettings                           MapdInputType = 10
	MapdInputType_setEnableSpeed                         MapdInputType = 11
	MapdInputType_setVisionCurveUseEnableSpeed           MapdInputType = 12
	MapdInputType_setMapCurveUseEnableSpeed              MapdInputType = 13
	MapdInputType_setSpeedLimitUseEnableSpeed            MapdInputType = 14
	MapdInputType_setHoldLastSeenSpeedLimit              MapdInputType = 15
	MapdInputType_setTargetSpeedJerk                     MapdInputType = 16
	MapdInputType_setTargetSpeedAccel                    MapdInputType = 17
	MapdInputType_setTargetSpeedTimeOffset               MapdInputType = 18
	MapdInputType_setDefaultLaneWidth                    MapdInputType = 19
	MapdInputType_setMapCurveTargetLatA                  MapdInputType = 20
	MapdInputType_loadDefaultSettings                    MapdInputType = 21
	MapdInputType_loadRecommendedSettings                MapdInputType = 22
	MapdInputType_setSlowDownForNextSpeedLimit           MapdInputType = 23
	MapdInputType_setSpeedUpForNextSpeedLimit            MapdInputType = 24
	MapdInputType_setHoldSpeedLimitWhileChangingSetSpeed MapdInputType = 25
	MapdInputType_loadPersistentSettings                 MapdInputType = 26
	MapdInputType_cancelDownload                         MapdInputType = 27
	MapdInputType_setLogJson                             MapdInputType = 28
	MapdInputType_setLogSource                           MapdInputType = 29
	MapdInputType_setExternalSpeedLimitControl           MapdInputType = 30
	MapdInputType_setExternalSpeedLimit                  MapdInputType = 31
	MapdInputType_setSpeedLimitPriority                  MapdInputType = 32
	MapdInputType_setSpeedLimitChangeRequiresAccept      MapdInputType = 33
	MapdInputType_acceptSpeedLimit                       MapdInputType = 34
	MapdInputType_setPressGasToAcceptSpeedLimit          MapdInputType = 35
	MapdInputType_setAdjustSetSpeedToAcceptSpeedLimit    MapdInputType = 36
	MapdInputType_setAcceptSpeedLimitTimeout             MapdInputType = 37
	MapdInputType_setPressGasToOverrideSpeedLimit        MapdInputType = 38
)

// String returns the enum's constant name.
func (c MapdInputType) String() string {
	switch c {
	case MapdInputType_download:
		return "download"
	case MapdInputType_setTargetLateralAccel:
		return "setTargetLateralAccel"
	case MapdInputType_setSpeedLimitOffset:
		return "setSpeedLimitOffset"
	case MapdInputType_setSpeedLimitControl:
		return "setSpeedLimitControl"
	case MapdInputType_setMapCurveSpeedControl:
		return "setMapCurveSpeedControl"
	case MapdInputType_setVisionCurveSpeedControl:
		return "setVisionCurveSpeedControl"
	case MapdInputType_setLogLevel:
		return "setLogLevel"
	case MapdInputType_setVisionCurveTargetLatA:
		return "setVisionCurveTargetLatA"
	case MapdInputType_setVisionCurveMinTargetV:
		return "setVisionCurveMinTargetV"
	case MapdInputType_reloadSettings:
		return "reloadSettings"
	case MapdInputType_saveSettings:
		return "saveSettings"
	case MapdInputType_setEnableSpeed:
		return "setEnableSpeed"
	case MapdInputType_setVisionCurveUseEnableSpeed:
		return "setVisionCurveUseEnableSpeed"
	case MapdInputType_setMapCurveUseEnableSpeed:
		return "setMapCurveUseEnableSpeed"
	case MapdInputType_setSpeedLimitUseEnableSpeed:
		return "setSpeedLimitUseEnableSpeed"
	case MapdInputType_setHoldLastSeenSpeedLimit:
		return "setHoldLastSeenSpeedLimit"
	case MapdInputType_setTargetSpeedJerk:
		return "setTargetSpeedJerk"
	case MapdInputType_setTargetSpeedAccel:
		return "setTargetSpeedAccel"
	case MapdInputType_setTargetSpeedTimeOffset:
		return "setTargetSpeedTimeOffset"
	case MapdInputType_setDefaultLaneWidth:
		return "setDefaultLaneWidth"
	case MapdInputType_setMapCurveTargetLatA:
		return "setMapCurveTargetLatA"
	case MapdInputType_loadDefaultSettings:
		return "loadDefaultSettings"
	case MapdInputType_loadRecommendedSettings:
		return "loadRecommendedSettings"
	case MapdInputType_setSlowDownForNextSpeedLimit:
		return "setSlowDownForNextSpeedLimit"
	case MapdInputType_setSpeedUpForNextSpeedLimit:
		return "setSpeedUpForNextSpeedLimit"
	case MapdInputType_setHoldSpeedLimitWhileChangingSetSpeed:
		return "setHoldSpeedLimitWhileChangingSetSpeed"
	case MapdInputType_loadPersistentSettings:
		return "loadPersistentSettings"
	case MapdInputType_cancelDownload:
		return "cancelDownload"
	case MapdInputType_setLogJson:
		return "setLogJson"
	case MapdInputType_setLogSource:
		return "setLogSource"
	case MapdInputType_setExternalSpeedLimitControl:
		return "setExternalSpeedLimitControl"
	case MapdInputType_setExternalSpeedLimit:
		return "setExternalSpeedLimit"
	case MapdInputType_setSpeedLimitPriority:
		return "setSpeedLimitPriority"
	case MapdInputType_setSpeedLimitChangeRequiresAccept:
		return "setSpeedLimitChangeRequiresAccept"
	case MapdInputType_acceptSpeedLimit:
		return "acceptSpeedLimit"
	case MapdInputType_setPressGasToAcceptSpeedLimit:
		return "setPressGasToAcceptSpeedLimit"
	case MapdInputType_setAdjustSetSpeedToAcceptSpeedLimit:
		return "setAdjustSetSpeedToAcceptSpeedLimit"
	case MapdInputType_setAcceptSpeedLimitTimeout:
		return "setAcceptSpeedLimitTimeout"
	case MapdInputType_setPressGasToOverrideSpeedLimit:
		return "setPressGasToOverrideSpeedLimit"

	default:
		return ""
	}
}

// MapdInputTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func MapdInputTypeFromString(c string) MapdInputType {
	switch c {
	case "download":
		return MapdInputType_download
	case "setTargetLateralAccel":
		return MapdInputType_setTargetLateralAccel
	case "setSpeedLimitOffset":
		return MapdInputType_setSpeedLimitOffset
	case "setSpeedLimitControl":
		return MapdInputType_setSpeedLimitControl
	case "setMapCurveSpeedControl":
		return MapdInputType_setMapCurveSpeedControl
	case "setVisionCurveSpeedControl":
		return MapdInputType_setVisionCurveSpeedControl
	case "setLogLevel":
		return MapdInputType_setLogLevel
	case "setVisionCurveTargetLatA":
		return MapdInputType_setVisionCurveTargetLatA
	case "setVisionCurveMinTargetV":
		return MapdInputType_setVisionCurveMinTargetV
	case "reloadSettings":
		return MapdInputType_reloadSettings
	case "saveSettings":
		return MapdInputType_saveSettings
	case "setEnableSpeed":
		return MapdInputType_setEnableSpeed
	case "setVisionCurveUseEnableSpeed":
		return MapdInputType_setVisionCurveUseEnableSpeed
	case "setMapCurveUseEnableSpeed":
		return MapdInputType_setMapCurveUseEnableSpeed
	case "setSpeedLimitUseEnableSpeed":
		return MapdInputType_setSpeedLimitUseEnableSpeed
	case "setHoldLastSeenSpeedLimit":
		return MapdInputType_setHoldLastSeenSpeedLimit
	case "setTargetSpeedJerk":
		return MapdInputType_setTargetSpeedJerk
	case "setTargetSpeedAccel":
		return MapdInputType_setTargetSpeedAccel
	case "setTargetSpeedTimeOffset":
		return MapdInputType_setTargetSpeedTimeOffset
	case "setDefaultLaneWidth":
		return MapdInputType_setDefaultLaneWidth
	case "setMapCurveTargetLatA":
		return MapdInputType_setMapCurveTargetLatA
	case "loadDefaultSettings":
		return MapdInputType_loadDefaultSettings
	case "loadRecommendedSettings":
		return MapdInputType_loadRecommendedSettings
	case "setSlowDownForNextSpeedLimit":
		return MapdInputType_setSlowDownForNextSpeedLimit
	case "setSpeedUpForNextSpeedLimit":
		return MapdInputType_setSpeedUpForNextSpeedLimit
	case "setHoldSpeedLimitWhileChangingSetSpeed":
		return MapdInputType_setHoldSpeedLimitWhileChangingSetSpeed
	case "loadPersistentSettings":
		return MapdInputType_loadPersistentSettings
	case "cancelDownload":
		return MapdInputType_cancelDownload
	case "setLogJson":
		return MapdInputType_setLogJson
	case "setLogSource":
		return MapdInputType_setLogSource
	case "setExternalSpeedLimitControl":
		return MapdInputType_setExternalSpeedLimitControl
	case "setExternalSpeedLimit":
		return MapdInputType_setExternalSpeedLimit
	case "setSpeedLimitPriority":
		return MapdInputType_setSpeedLimitPriority
	case "setSpeedLimitChangeRequiresAccept":
		return MapdInputType_setSpeedLimitChangeRequiresAccept
	case "acceptSpeedLimit":
		return MapdInputType_acceptSpeedLimit
	case "setPressGasToAcceptSpeedLimit":
		return MapdInputType_setPressGasToAcceptSpeedLimit
	case "setAdjustSetSpeedToAcceptSpeedLimit":
		return MapdInputType_setAdjustSetSpeedToAcceptSpeedLimit
	case "setAcceptSpeedLimitTimeout":
		return MapdInputType_setAcceptSpeedLimitTimeout
	case "setPressGasToOverrideSpeedLimit":
		return MapdInputType_setPressGasToOverrideSpeedLimit

	default:
		return 0
	}
}

type MapdInputType_List = capnp.EnumList[MapdInputType]

func NewMapdInputType_List(s *capnp.Segment, sz int32) (MapdInputType_List, error) {
	return capnp.NewEnumList[MapdInputType](s, sz)
}

type WaySelectionType uint16

// WaySelectionType_TypeID is the unique identifier for the type WaySelectionType.
const WaySelectionType_TypeID = 0xfa3e5ce74e25e82a

// Values of WaySelectionType.
const (
	WaySelectionType_current   WaySelectionType = 0
	WaySelectionType_predicted WaySelectionType = 1
	WaySelectionType_possible  WaySelectionType = 2
	WaySelectionType_extended  WaySelectionType = 3
	WaySelectionType_fail      WaySelectionType = 4
)

// String returns the enum's constant name.
func (c WaySelectionType) String() string {
	switch c {
	case WaySelectionType_current:
		return "current"
	case WaySelectionType_predicted:
		return "predicted"
	case WaySelectionType_possible:
		return "possible"
	case WaySelectionType_extended:
		return "extended"
	case WaySelectionType_fail:
		return "fail"

	default:
		return ""
	}
}

// WaySelectionTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func WaySelectionTypeFromString(c string) WaySelectionType {
	switch c {
	case "current":
		return WaySelectionType_current
	case "predicted":
		return WaySelectionType_predicted
	case "possible":
		return WaySelectionType_possible
	case "extended":
		return WaySelectionType_extended
	case "fail":
		return WaySelectionType_fail

	default:
		return 0
	}
}

type WaySelectionType_List = capnp.EnumList[WaySelectionType]

func NewWaySelectionType_List(s *capnp.Segment, sz int32) (WaySelectionType_List, error) {
	return capnp.NewEnumList[WaySelectionType](s, sz)
}

type SpeedLimitOffsetType uint16

// SpeedLimitOffsetType_TypeID is the unique identifier for the type SpeedLimitOffsetType.
const SpeedLimitOffsetType_TypeID = 0xa5a3dfadcac04344

// Values of SpeedLimitOffsetType.
const (
	SpeedLimitOffsetType_static  SpeedLimitOffsetType = 0
	SpeedLimitOffsetType_percent SpeedLimitOffsetType = 1
)

// String returns the enum's constant name.
func (c SpeedLimitOffsetType) String() string {
	switch c {
	case SpeedLimitOffsetType_static:
		return "static"
	case SpeedLimitOffsetType_percent:
		return "percent"

	default:
		return ""
	}
}

// SpeedLimitOffsetTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func SpeedLimitOffsetTypeFromString(c string) SpeedLimitOffsetType {
	switch c {
	case "static":
		return SpeedLimitOffsetType_static
	case "percent":
		return SpeedLimitOffsetType_percent

	default:
		return 0
	}
}

type SpeedLimitOffsetType_List = capnp.EnumList[SpeedLimitOffsetType]

func NewSpeedLimitOffsetType_List(s *capnp.Segment, sz int32) (SpeedLimitOffsetType_List, error) {
	return capnp.NewEnumList[SpeedLimitOffsetType](s, sz)
}

type MapdIn capnp.Struct

// MapdIn_TypeID is the unique identifier for the type MapdIn.
const MapdIn_TypeID = 0xc86a3d38d13eb3ef

func NewMapdIn(s *capnp.Segment) (MapdIn, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdIn(st), err
}

func NewRootMapdIn(s *capnp.Segment) (MapdIn, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MapdIn(st), err
}

func ReadRootMapdIn(msg *capnp.Message) (MapdIn, error) {
	root, err := msg.Root()
	return MapdIn(root.Struct()), err
}

func (s MapdIn) String() string {
	str, _ := text.Marshal(0xc86a3d38d13eb3ef, capnp.Struct(s))
	return str
}

func (s MapdIn) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdIn) DecodeFromPtr(p capnp.Ptr) MapdIn {
	return MapdIn(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdIn) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdIn) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdIn) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdIn) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdIn) Type() MapdInputType {
	return MapdInputType(capnp.Struct(s).Uint16(0))
}

func (s MapdIn) SetType(v MapdInputType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s MapdIn) Float() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s MapdIn) SetFloat(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s MapdIn) Str() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MapdIn) HasStr() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdIn) StrBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MapdIn) SetStr(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s MapdIn) Bool() bool {
	return capnp.Struct(s).Bit(16)
}

func (s MapdIn) SetBool(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

// MapdIn_List is a list of MapdIn.
type MapdIn_List = capnp.StructList[MapdIn]

// NewMapdIn creates a new list of MapdIn.
func NewMapdIn_List(s *capnp.Segment, sz int32) (MapdIn_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[MapdIn](l), err
}

// MapdIn_Future is a wrapper for a MapdIn promised by a client call.
type MapdIn_Future struct{ *capnp.Future }

func (f MapdIn_Future) Struct() (MapdIn, error) {
	p, err := f.Future.Ptr()
	return MapdIn(p.Struct()), err
}

type RoadContext uint16

// RoadContext_TypeID is the unique identifier for the type RoadContext.
const RoadContext_TypeID = 0xabefa88b9563dbae

// Values of RoadContext.
const (
	RoadContext_freeway RoadContext = 0
	RoadContext_city    RoadContext = 1
	RoadContext_unknown RoadContext = 2
)

// String returns the enum's constant name.
func (c RoadContext) String() string {
	switch c {
	case RoadContext_freeway:
		return "freeway"
	case RoadContext_city:
		return "city"
	case RoadContext_unknown:
		return "unknown"

	default:
		return ""
	}
}

// RoadContextFromString returns the enum value with a name,
// or the zero value if there's no such value.
func RoadContextFromString(c string) RoadContext {
	switch c {
	case "freeway":
		return RoadContext_freeway
	case "city":
		return RoadContext_city
	case "unknown":
		return RoadContext_unknown

	default:
		return 0
	}
}

type RoadContext_List = capnp.EnumList[RoadContext]

func NewRoadContext_List(s *capnp.Segment, sz int32) (RoadContext_List, error) {
	return capnp.NewEnumList[RoadContext](s, sz)
}

type MapdOut capnp.Struct

// MapdOut_TypeID is the unique identifier for the type MapdOut.
const MapdOut_TypeID = 0xa4f1eb3323f5f582

func NewMapdOut(s *capnp.Segment) (MapdOut, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 5})
	return MapdOut(st), err
}

func NewRootMapdOut(s *capnp.Segment) (MapdOut, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 5})
	return MapdOut(st), err
}

func ReadRootMapdOut(msg *capnp.Message) (MapdOut, error) {
	root, err := msg.Root()
	return MapdOut(root.Struct()), err
}

func (s MapdOut) String() string {
	str, _ := text.Marshal(0xa4f1eb3323f5f582, capnp.Struct(s))
	return str
}

func (s MapdOut) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MapdOut) DecodeFromPtr(p capnp.Ptr) MapdOut {
	return MapdOut(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MapdOut) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MapdOut) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MapdOut) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MapdOut) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MapdOut) WayName() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MapdOut) HasWayName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MapdOut) WayNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MapdOut) SetWayName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s MapdOut) WayRef() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s MapdOut) HasWayRef() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s MapdOut) WayRefBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s MapdOut) SetWayRef(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s MapdOut) RoadName() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s MapdOut) HasRoadName() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s MapdOut) RoadNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s MapdOut) SetRoadName(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s MapdOut) SpeedLimit() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s MapdOut) SetSpeedLimit(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s MapdOut) NextSpeedLimit() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s MapdOut) SetNextSpeedLimit(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s MapdOut) NextSpeedLimitDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(8))
}

func (s MapdOut) SetNextSpeedLimitDistance(v float32) {
	capnp.Struct(s).SetUint32(8, math.Float32bits(v))
}

func (s MapdOut) Hazard() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s MapdOut) HasHazard() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s MapdOut) HazardBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s MapdOut) SetHazard(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s MapdOut) NextHazard() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s MapdOut) HasNextHazard() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s MapdOut) NextHazardBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s MapdOut) SetNextHazard(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s MapdOut) NextHazardDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(12))
}

func (s MapdOut) SetNextHazardDistance(v float32) {
	capnp.Struct(s).SetUint32(12, math.Float32bits(v))
}

func (s MapdOut) AdvisorySpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(16))
}

func (s MapdOut) SetAdvisorySpeed(v float32) {
	capnp.Struct(s).SetUint32(16, math.Float32bits(v))
}

func (s MapdOut) NextAdvisorySpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(20))
}

func (s MapdOut) SetNextAdvisorySpeed(v float32) {
	capnp.Struct(s).SetUint32(20, math.Float32bits(v))
}

func (s MapdOut) NextAdvisorySpeedDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(24))
}

func (s MapdOut) SetNextAdvisorySpeedDistance(v float32) {
	capnp.Struct(s).SetUint32(24, math.Float32bits(v))
}

func (s MapdOut) OneWay() bool {
	return capnp.Struct(s).Bit(224)
}

func (s MapdOut) SetOneWay(v bool) {
	capnp.Struct(s).SetBit(224, v)
}

func (s MapdOut) Lanes() uint8 {
	return capnp.Struct(s).Uint8(29)
}

func (s MapdOut) SetLanes(v uint8) {
	capnp.Struct(s).SetUint8(29, v)
}

func (s MapdOut) TileLoaded() bool {
	return capnp.Struct(s).Bit(225)
}

func (s MapdOut) SetTileLoaded(v bool) {
	capnp.Struct(s).SetBit(225, v)
}

func (s MapdOut) SpeedLimitSuggestedSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(32))
}

func (s MapdOut) SetSpeedLimitSuggestedSpeed(v float32) {
	capnp.Struct(s).SetUint32(32, math.Float32bits(v))
}

func (s MapdOut) SuggestedSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(36))
}

func (s MapdOut) SetSuggestedSpeed(v float32) {
	capnp.Struct(s).SetUint32(36, math.Float32bits(v))
}

func (s MapdOut) EstimatedRoadWidth() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(40))
}

func (s MapdOut) SetEstimatedRoadWidth(v float32) {
	capnp.Struct(s).SetUint32(40, math.Float32bits(v))
}

func (s MapdOut) RoadContext() RoadContext {
	return RoadContext(capnp.Struct(s).Uint16(30))
}

func (s MapdOut) SetRoadContext(v RoadContext) {
	capnp.Struct(s).SetUint16(30, uint16(v))
}

func (s MapdOut) DistanceFromWayCenter() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(44))
}

func (s MapdOut) SetDistanceFromWayCenter(v float32) {
	capnp.Struct(s).SetUint32(44, math.Float32bits(v))
}

func (s MapdOut) VisionCurveSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(48))
}

func (s MapdOut) SetVisionCurveSpeed(v float32) {
	capnp.Struct(s).SetUint32(48, math.Float32bits(v))
}

func (s MapdOut) MapCurveSpeed() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(52))
}

func (s MapdOut) SetMapCurveSpeed(v float32) {
	capnp.Struct(s).SetUint32(52, math.Float32bits(v))
}

func (s MapdOut) WaySelectionType() WaySelectionType {
	return WaySelectionType(capnp.Struct(s).Uint16(56))
}

func (s MapdOut) SetWaySelectionType(v WaySelectionType) {
	capnp.Struct(s).SetUint16(56, uint16(v))
}

func (s MapdOut) SpeedLimitAccepted() bool {
	return capnp.Struct(s).Bit(226)
}

func (s MapdOut) SetSpeedLimitAccepted(v bool) {
	capnp.Struct(s).SetBit(226, v)
}

func (s MapdOut) NextStopSign() bool {
	return capnp.Struct(s).Bit(227)
}

func (s MapdOut) SetNextStopSign(v bool) {
	capnp.Struct(s).SetBit(227, v)
}

func (s MapdOut) NextStopSignDistance() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(60))
}

func (s MapdOut) SetNextStopSignDistance(v float32) {
	capnp.Struct(s).SetUint32(60, math.Float32bits(v))
}

// MapdOut_List is a list of MapdOut.
type MapdOut_List = capnp.StructList[MapdOut]

// NewMapdOut creates a new list of MapdOut.
func NewMapdOut_List(s *capnp.Segment, sz int32) (MapdOut_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 64, PointerCount: 5}, sz)
	return capnp.StructList[MapdOut](l), err
}

// MapdOut_Future is a wrapper for a MapdOut promised by a client call.
type MapdOut_Future struct{ *capnp.Future }

func (f MapdOut_Future) Struct() (MapdOut, error) {
	p, err := f.Future.Ptr()
	return MapdOut(p.Struct()), err
}

const schema_b526ba661d550a59 = "x\xda\x94X}\x8c\x15\xe5\xd5?g\x9e{\xf7\xee." +
	"\x1f\xf7^\x9e\x0b\x82\xc8\xbb\xa2b\xde\x97\xc8+\xeb\xca" +
	"+\xe0\xc7\xba\xec\xc2\x8b\x9bEv\x18pe\x83\x89\xb3" +
	"w\x9e\xdd\x1d\x9c\x9d\xb9\xce<w\x97Kx\xc3[\x8a" +
	"\x89\xa51\x9aV\x8d\x18\x88\x1f@bm\x15j\xa5\xb5" +
	"\xc4\xa6\x95h\xc2R7\x01S\x9a\xa25\x8a\xadA\xac" +
	"Fm%U+\x99\xe6<s\xbf\x16n\x0b\xfb\xd7\xdd" +
	"\xf9\x9d\xdf\x9c\xaf\xe7\xcc9\xe7\xd9\x85\x0b\xebn\x8f5" +
	"O\xd9\xdf\x08\x9a\xbe%^\x17\xa6\xef[\xff\x81+_" +
	"\xfc\x7fH\xcf\xc6p}\xe3\xba9\xfd\x87\xae=\x08\xb1" +
	"\x04@\xcb\xad\xf1^\xe4z<\x01,\xdc\xffe\xd7\x92" +
	"\xde\xcf\x0f\x7f\xa7\x06k\x01\xb1\xda\x14\xeb\xee\xf6\xc3\x0f" +
	"\xf7]\xfb\xd4\x03\x90\x9e\xadUX\x80-s\xe2\x9d\xc8" +
	"\x9b\xe3\x11}?\x03\x0c\xa7\xbd\x8c\x03\x03G\xc6v\xd5" +
	"Px\xa6\xbe\x0f\xf9\xb9zR\xb8\xe0\x9d&\xd6\x91\x18" +
	"|\xa6\x06\xebd}/\xf2O\x15\xcba-\xb7\x7f\xd5" +
	"W\xb7g<+\xce\x886J\xb4w\xeb\x13\x00\xfcd" +
	"\xfd~\xc0p\xdb\xd9\xb3W\xb7\xfc\xe5\x8b\xbd\xa0\xcf\xc6" +
	"\xfa*\xb6r\xee\xa1\x86\xcb\x91\xefn\xa0?w6\xfc" +
	"\"\x0e\x18v\xb4\xff\xe6\xe8\x0b\xef\xed\xd9waH\xa9" +
	"m\xc8\x9bS\xa4xA\xea&\xc0p\xdd^\xfd\xe4u" +
	"\xc3c\xfbj\xf8\xda\x9c\xeaE\xbe<E\xbe\xbe\xf8N" +
	"\xf6\xb1\xef?\xf7\xd9\x8f/\xd077\xb5\xb4\xa2o5" +
	"`x\xcf\xc1\xd3\xcd\x0f\x9f{\xef\xc5\x1a\xfa\xdaH\xdf" +
	":\xa5\xaf\xf5\xbd\x8f\xffo\xd5\x95=\x07jZ\xed+" +
	"Y=\x82]s\xed\xac\xfbJ\x0d\xd6\\\xd2\xb5H\xb1" +
	"\x06_\xfd\xe1\xa3\xc6\xcd\x1d\xbf\xaa\xc1J\x93\xaey\x8a" +
	"\xb5\x9d\xdd\xf8\xbe\xb8\xe5\x9a\xc35XH\xac\xe9\x8a\xf5" +
	"\xd9\xcfn;\xbe\xf8\xd6\x8dG(\xcd\xd5\x87\x82\xc4\xfb" +
	"\"9\x0d9\xaaX\xcf%O\x03\x86K\xd7\xf7\xe4\x9c" +
	"\x13O\xfd\xb6\x86\xce\xe3\xa4\xf3C\xa5\xf3\xd8\xb6\xa7\x07" +
	"\xfe\xf1\xf6\xe3c5X\xaf\x11\xeb\x84b-Y\xf2\xea" +
	"3o\xee\xf8\xfb\xef\xc92;\x8f\xf6\xd3T'\xf27" +
	"\x94\xe1\xd7RdxQW\xc7w\x9f\xe8y\xfc\xed\x1a" +
	"*\xf7\xa5{\x91\xff2M*\x0f\xbb\xbf\x9et\xd7\xeb" +
	"\x1b\xfeV\x83\xf5\x18\xb1~\xa4X\xb3v\xef\xbe\xa3\xe1" +
	"\x93\x19_\xd6`=@\xac\x9d\x8a\xb5'\x96;w\xf3" +
	"\xf6\x87\xbe\xae\xc1\xca\x13\xeb{\x8a5\xff\xa3yw\x9e" +
	"\xdep\xdb7\x17\x94\x89H\xf7!/\xa4)\x82|z" +
	"+`\xf8l\xd0}\xe4\xe8={\xbe\xa1p\xab\xa8q" +
	"\x8d4\x1eLoC>J\xec\x967\xd2=\x08\x18\xa6" +
	"\x7f>\xf2\xe0\xa7m}\xdf\xd60\xbf\x9c\xf7!_\xcf" +
	"\xc9\xfc\xd6'\x0e\x9c6\x9ex0\xacyz\x8b\xf8!" +
	"\xe4\xab8\xb9p\x07\xdf\x0f\x0b\xc2\xac\xf0\x85\xe9\\\x9f" +
	"\x8d\xe5\x03\xe9\x0d]\x9fU?\xff\x9d5snni" +
	"\xbbzX#\x02\xe1\x0f\x0bf\xdd\xd8\x8d8\x11\xfe\xc2" +
	"\x8b\xf1W\x999\xeb\x0e7\x97\x97k\x0b9\x01\xd0\x8d" +
	"\xa8\xefB\x0d\x80\x8fa'\x00\"\x1f\xc5\x97\x00P\xe3" +
	"\xa3\xf8,\x002>\x8a\xcf\x03`\x8c\x8f\xe2a\x00\x8c" +
	"\xf3Q|\x1b\x00\xeb\xf8\x18\xf6\x01`\x82\x8f\xe2Q\x00" +
	"\xac\xe7c\xea\xb7\x81\x1f\xc7\xcd\x00\xd8\xc8\xc7p#\x00" +
	"N\xe2\xa3\xeay2\x7f\x03?\x06\xc0)|\x14\xdf\x02" +
	"\xc0\xa9|\x0c?\x00\xc0$?\xae\x9eS\xfc\x04>\x09" +
	"\x80i~B\xd9\x9d\xc6O(}\x9c\x9fT\xcf\x19~" +
	"R\xf95\xbd\xf8<\x83\x9fT\xfe\\\xc6O*\xbd3" +
	"\xf9\xbbJ\xdf\xac\x96S\xb8\x14\x01\xf0r~\x06\x0f\x01" +
	"\xe0l~F9p\x05\xff\x10{\x01p\x0e?\xa5\x1c" +
	"\xfb\x0f\xfe\xaez\xb1\x89\x9fR\x8a\xaf,\xfe\xcem9" +
	"\x85\xd3H\xc1U\xfc\x0c\xee\x00\xc0\xab\xf9\x19\xfc+\x00" +
	"^\xd3\xf2)^E\x82y\xfc\xacJ\xc1\xb5-_\xa3" +
	"\x86\x00\xa1\xe5\x8d\xb8\x8egZ\x00\x10\x06B\xae5\xfd" +
	"\x01\x81\xb2\xcb\x94\xc27\x9d\xa6\xb6lV8\x84\x1b9" +
	"!,\xec\xb2\x87l\xb9\xba\xbf?\x11\x08y\x1e\xda\xee" +
	"\xb9I\xe9{\x8a\xbc\xca\xcc\xb5\xe7\xe3\xfe\xb0P\xf2v" +
	"\xcf%\x01\x04B\xdee\x07\xb6\xe7\xb6\xe7\xc7\x89X\xf4" +
	"R\x977\xd0% 1\x1c\xd9SL-\xa2*\x9f\xc8" +
	"\xa5\xb6\xc8\xc7j\xd9*\xdb\x8d\xc4w\x01\x84\xbe\xa0H" +
	"\x0c\x01\xadR\xda\xee@\x10\x06\xe6\xb00\x84\x94\x90\x8c" +
	"\x1e\x85\\\xee\x9a}\x0e\xb4F\xe6\xcfW\xb6.\x10J" +
	".\x8cdI\xacB\xd1\xc6\xc9rB\xa0U\x8e^S" +
	"\xd1WI\x13\xc57Wz\x8e\xd5\xa5\x99\x814\x84p" +
	"\x15\x95\x98(\xab\xb2\xac\xd0N\xc1\xfc\xfb\xce\x07\xdb\xb2" +
	"\x89b\xe2\x15\xaaE\xe8Z{H\xac\xee\xef\x0f\x84\x8c" +
	"\x12\xd1!\xfa\xcd<:\xb2\xcbtE\x8f\x9d\xb0\xe4`" +
	"\xd9e,\xe5\xadI%.\xa4\xc4\x10\x1d\xf3\x8e\xa4\x8c" +
	"\xd8\x09J\x08\xa1kD\xd6\x8b\x0f\x0d\x09\xd7\x12\x96\x92" +
	"\xb8\x03\x01\x9d\x95\xe1x#\x1d\xde\x88\xbb\xc2\xf3\xef\x14" +
	"\x9b\"\x07\xba\x92\x14l%\xf6u\xb9qR;Q\x94" +
	"R\xec\x06+\xc5,{\x06mG\xb4\x0f\x9a\xee\x80\xed" +
	"\x0e\x18\xa25\xa2+\xeb\xdd\xc2\x0f\xd0\x0e\xa4p%\x09" +
	"\xa2c\xcb\x9anV8\x1d\x1e\xb4F\xb5Y,\x8f\xce" +
	"\x00\x98\xe7\x16\x1f\x0c\x0f\x92y?+\xd4\xa1n\x92\xc2" +
	"\xd7\\\xd3)\xa7y\\9*1\x96\xc4M]\xe3b" +
	"\x88\xaa\xb7\xdb\xb7\x9b<\xdf\x96\x852\xce\"5\xe4\xb4" +
	"X#\xee\xcf\xdb\xbe\x08\xe8k\xc8\xa1\x0cM\xfa\x95F" +
	"\x0eK\xd6\xa2\xe3\xe8\xf6E\x10h\xffk\x06k\xbd\xb6" +
	"\"c\x9c\xbd6kc>`\x94\xfe\xe84\xabY\x95" +
	"\xdc)P\x93\x95P\xe8\xd4=\x96\x97e\x13\xf5\xca\xc4" +
	"\xeaa\xe1\xfb\xb6%*D(\xb5\xce\x8bu\xda\x84\xd5" +
	"|\xc3\x04[\xf3\x92Ki\xcd\x94h*\xa3\xd5,/" +
	"\xa97Of1\x80\x18\x02\xa4\x97\xef\x00\xd0W2\xd4" +
	"\xd7j\x98F\xcc \x81z'\x80\xde\xcdP\xdf\xa0a" +
	"Z\xd32\xd4\xc9\xd3\xeb\xe7\x03\xe8k\x19\xea9\x0d\xcb" +
	"\xcd\x09\xbb}o\x80B\xa7f[\x19\x82\x80\x98\x02\xa4" +
	"\xbcDUK\xad\x1a4\x9c\x0c\x98\xcc\x99r\x10\xa7\x02" +
	"v3\xc4TeK\x00$\xb0\x1c\x08\xfb\x17\x81\x94\x02" +
	"\x18,\x05\xc0G\xb5e\x00\xc6\xeb\x1aC\xe3\x98V\x89" +
	"\x81\x8fiK\x01\x8c#\x84\xffN\xab\x84\xc1\x8fk\x9d" +
	"\x00\xc61\xc2\xff\xa8i\x88,\x83\x8c\xb6R\xad\x17\xc0" +
	"\xf8\x03\xc1\x7f&z\x0c3\x18\x03\xe0\xa7\xb4\xcd\x00\xc6" +
	"\xfb\x84\x7fBx\\\xcb`\x1c\x80\x9f\xd1\x0e\x01\x18\x9f" +
	"\x10\xfe\x15\xe1u,\x83u\x00\xfc\xac2\xfb9\xe1\xdf" +
	"\x12\x9e\x88ehZ\xf3\xaf\x95\xfe\xaf\x08\x8f1\x0d\xd3" +
	"\xf5,\x83\xf5\x00\x1c\xd9\x93\x00F\x8c14R\x847" +
	"\xc42\xd8\x00\xc0\xa70\x1f\xc0\x98L\xf8L\xc2\x1b\xe3" +
	"\x19l\x04\xe0\xd3\xd9\x0f\x00\x8c\x99\x84_C\xf8\xa4\xba" +
	"\x0cN\x02\xe0s\xd9[\x00\xc6\x7f\x12~#\xe1\x93\xdf" +
	"\xcf\xe0d\x00\xde\xcc\xc8\x9f\xeb\x08_L\xf8\x949\x19" +
	"\x9c\x02\xc0\x17\xb1\x1b\x00\x8c\x85\x84\xdfB\xf8\xd4S\x19" +
	"\x9c\x0a\xc0\x970\xf2s1\xe1\x1d\x84'\xeb3\x98\x04" +
	"\xe0m\xec(\x80\xb1\x92\xf0\xb5\x84\xa7\x1a2\x98\x02\xe0" +
	":\xa3\xfct\x13\xbe\x81\xf0tc\x06\xd3\x00|\xbd\x8a" +
	"k\x03\xe1\x83\x84OKfp\x1a\x00\x17\xac\x0f\xc0\xb0" +
	"\x08\xcf\x11\xce'e\x90\x03\xf0!\xf6\x12\x80\x91#|" +
	"\x0b\xe1\x99\xc9\x19\xcc\x00\xf0\x02\xdb\x01`l!\xfcA" +
	"\xc2\xa7O\xc9\xe0t\x00\xfe\x80\xca\xcfv\xc2\x1f!|" +
	"\xc6\x15\x19\x9c\x01\xc0\x1fR\xfcG\x08\xdfE\xf8e\x1f" +
	"d\xf02\x00\xbeS\xf9\xb3\x8b\xf0\xe7\x08\x9f\xf9\xa7\x0c" +
	"\xce\x04\xe0\xfb\xd8F\x00c/\xe1\x07\x08\x9f\x95\xcc\xe0" +
	",\x00\xfe\x02{\x1e\xc08@\xf8\xabL\xc3\xad#f" +
	"\xe1NsH\x94\xca\xb8u\xc4,\xac\x11\xfd\xa5\xc7\xd0" +
	"\xf7L\x8b\xe4U\x95\x1e\x06\xc5\xef\x1f\x98-\xb1\x114" +
	"l\x04\x0c\xddbO\x86\xd6\xa85\\ \xc0\x08\xef\xb0" +
	"[\x03I\xdd\xb6Dh\x1d47\x9b\xbeU\xd6N\xfc" +
	"\x95\xe6f\x13X\x0d\x10}\xab\xc3\xa6\xf7YEAh" +
	"Z\xc3v\xe0\xf9\x05h\x8a\xfak\xb5\xe56k\xd8F" +
	"\x12F.\\ \xd3J\xb2\xa2\xde,V\x1c\xf3\\\xd1" +
	"c\x16\x10AC\x04lrLW\x04X\x07\x1a\xd6\x01" +
	"\x86\xd2vD\x17m1LX%J93\x9a-\x8d" +
	"\xfc\xc0\x80\x08\xa4\xb0\x94rZ\xf1\x8a\x96\x83\xa2\x00Z" +
	"\xad\xf1\xee\x8a@\xdaC\xa6\x14h\xad\xf1L\xab\xc7\xb6" +
	"\x98\x1c,\x0b\xe9\x1chw\x81\x84\xd8$1Y\xb9\xe7" +
	"\x01b\x120\xb4\xecbVW\xf8\xdeP\x8fYho" +
	"\x12.\xcd\xa0\xd2\xfb\xc3\xc5=\x08K\x8bP\x95GC" +
	"4\xbe\xfdaq~\xfeF\xcc\x82!\x1c\x91Ei{" +
	"n\xb4\xffb\xb2ru(Z.\xc5\x8cv4Hd" +
	"uB\xd4\xe1K/\x07I\xc3\x1ep/\x80\x91PJ" +
	"|\xb2\xba\"\xca\xcd2^\xa3YV\x86O\xb4\x97(" +
	"\xbf\xa8s\xd6\xabf\x9e^J~\xa5\x1b\x96\x01P\x9d" +
	"I;\xbb5'\xfc\xacp\xe5Df\xcf\xa2\xea\xd9S" +
	"\xabe\xd3\x09\xb5\xb7z\xae\x14\x9b\xa2\xb9\xa3\x8c\xcfY" +
	"\xa6\x8cO\x9fO7\x82\xf4\x94e\x00[\xfb}!F" +
	"\xccB2k\xcb\xc2\xd6\xbc{\x9f\xeb\x8d\xb8\x13\xf1\xa4" +
	"yBS3a5O\xf4\x06t\xd3D\x0d,\x9a\xe8" +
	"\x0b\xcd\x17K\xa6\xbac\xa1KyL\x95\xe7\xb7IS" +
	"y\x03C}\xb0j~\x8b\x1b\x00\xf4{\x19\xea\x8e\x86" +
	"X\x1c\xdf\xf6U\x00\xba\x15\x8d\xef4K\xa9\xa9\x97\x1e" +
	"\xa2\xb7\x07\x19\xeaR\xc3\xa4,\xe4\x04&+\xff=\x8a" +
	"\x0a\xb7\xa9\xdf\xf1\xccr\x9bJ\x04\xd2/\x8f\xf2>\xcf" +
	"s\xca\xb5:\x91P\x17N47-\x97\xb2\xe4t\x9b" +
	"r\xb0\xdb\xb3]\x19\xdd?\xabr\xd4YIG9G" +
	"\xf6\x9aJ\xe8i-\x16%\xe9~\x02s\x0c\xf5-\x94" +
	"\xa4x\x94\xa4\xc2f\x00}\x13C}\xbb\x86\xa1cJ" +
	"[\xe6-\xd5\xe8'\x81\x86\x93\x00C\xc7s\x07\x08\x04" +
	"\x14e,\x9b\xf7\x87M\x99\xf7\xa1\xd2(C\x19\xdd\x87" +
	"\x04\xb4:\x1e\x15\xfa\x05\x1f\xf2%\xd4a\xcb\x04\xebv" +
	"\xa2\xeb\xe4\xe2\x09\xf2\xff\xe7b\xfc\x9ebwT\xcd1" +
	"Q\xc8\x09:\x9b(\xdb\x8b\xa2>\xb0`\x8d\xea\x03\xff" +
	"\xd5\x09\x80,=\x8f~b\xe9\xb9\xf3\x01\xb6f\xf3\xbe" +
	"O-)\xe7\x0b\xcb\xceJ\x01h\x859/\x08\xec>" +
	"\x87\x0e \x14\xc5\xb5\x16\x00\x92\xfd\xa6\xed\xfc\xdb\x8eH" +
	"%\xd2Q\\[\xcb[+93\xb3\\(;\x97\x02" +
	"\xe8\x8f2\xd4\x9f\xae*\x94\xddT\x13\xbb\x18\xea\xcfQ" +
	"\xa1`\xe4\xfa\xbe^\x00}/C\xfd\x00\x15\x8a\x16\x15" +
	"\xca\x0b\xdb\x00\xf4\x9f0\xd4_\xd1\x10cj\x7fL\x1f" +
	"\xa4\xb7_f\xa8\x1f\xa3\xe5\x11\xd5\xf2\x98\x1e#\xe2\x9b" +
	"\x0c\xf5\x8f4l5\xb3\xd2\x1e\x16\x95\xefH]\xb1\x1c" +
	"\x8a\xb5\x8cIO\x9a\xce\x0a\xdb\x01&\x02\xac\x07\x0d\xeb" +
	"\xa1j\x05\x17\xd6\x0a\xdb\x11\x01\x94%\x8e\x975)\xdd" +
	"\x80Ai\xd3\xa6Ovj\x95\x08;\x844m'\x80" +
	"\xca*^\xfeg\xd3y\xab\xf8\xa5|\x9f\xe3\xaa\xe0b" +
	"\xc9\xef*\xfa\xd0\xd1\x1a\xf9p\xde\x85\x84>\xd6\x0e\x86" +
	"z\xb7\x86\xa5#XE\xd9\xeeb\xa8\xdf]u\x04\xeb" +
	"\xb6\x15\xef#\xf7jU!W\xed_\x13\xcb\xda?\x03" +
	"\x00\x00\xff\xff\x03=\xb1\xb5"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b526ba661d550a59,
		Nodes: []uint64{
			0x80ae746ee2596b11,
			0x81c2f05a394cf4af,
			0x859f26628fc24358,
			0x9ccdc8676701b412,
			0xa1680744031fdb2d,
			0xa30662f84033036c,
			0xa4f1eb3323f5f582,
			0xa5a3dfadcac04344,
			0xa5cd762cd951a455,
			0xabefa88b9563dbae,
			0xaedffd8f31e7b55d,
			0xb057204d7deadf3f,
			0xb86e6369214c01c8,
			0xbd443b539493bc68,
			0xc2243c65e0340384,
			0xc86a3d38d13eb3ef,
			0xcb9fd56c7057593a,
			0xcd96dafb67a082d0,
			0xd6f78acca1bc3939,
			0xda96579883444c35,
			0xf35cc4560bbf6ec2,
			0xf416ec09499d9d19,
			0xf98d843bfd7004a3,
			0xfa3e5ce74e25e82a,
			0xfaa35dcac85073a2,
			0xfc6241ed8877b611,
			0xff889853e7b0987f,
		},
		Compressed: true,
	})
}
