name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      # This step sets up emulation, which is good practice for cross-compilation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # This step installs Earthly
      - name: Install Earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-cache: true
          version: "latest"

      # This step checks out your code
      - name: Checkout
        uses: actions/checkout@v4

      # This is the ONLY build step we need. It builds the ARM64 binary.
      - name: Build Release Binary (arm64 for comma device)
        run: earthly +build-release

      # This step creates the release and uploads the binary from the build/ directory
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/mapd
          generate_release_notes: true
